### ISSUE TITLE
passport?

### ISSUE THREAD

**Issue by lafama** [linnovate/mean-logger#5]
Why do we need references to passport in this module?

**Comment by liorkesos** [comment]
we don't.

On Wed, Apr 2, 2014 at 12:37 AM, Denis Ndwiga notifications@github.comwrote:

> Why do we need references to passport in this module?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/linnovate/mean-logger/issues/5
> .

## 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by lafama** [comment]
And why do we need this module btw?

**Comment by liorkesos** [comment]
We don't, but this is the only way we can have any idea of the install base
of mean (by tracking its download).
Were about to introduce a few "core" modules and then I can drop the
dependency.
Lior
